version: '3.8'

services:

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - '3308:3306'
    environment:   
      MYSQL_ROOT_PASSWORD: password # Your password
      MYSQL_DATABASE: mysqldb
    networks:
      - python-network
    volumes: 
      - "db-volume:/var/lib/mysql"

  webscraping:
    container_name: web-scraping
    ports: 
      - "5678:5678"
    build:
      context: web-scraping
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    networks:
      - python-network
    volumes: 
      - ".:/usr/src/"

volumes:
  db-volume:

networks:
  python-network:
    driver: bridge